### ISSUE TITLE
Problem with installation, no biopython in requirements.txt

### ISSUE THREAD

**Issue by gitstanoje** [STOmics/Stereopy#222]
Hi,
I installed Version 1.0.0 directly from your GitHub ( as Development Version in your installation guide ). When I tried to run it  I got the following error: ModuleNotFoundError: No module named 'Bio'. I checked the requirements.txt file and there was no biopython library in it. I installed biopython with pip and everything vas okej. Could you consider adding biopython in the requirements.txt file?

**Comment by Zhenbin24** [comment]
Hello, may I ask why you want to install the dev version environment and what is your purpose. If you are just using it, we recommend using pip install to install it.

**Comment by tanliwei-coder** [comment]
The python packages version controlling seems to have problem when you install by "python setup.py install", if you want to develop Stereopy, you can install the necessary packages by running "pip install -r requirements.txt" before running "python setup.py install", otherwise, if you only want to use stereopy, we recommend you to install it directly by "pip install stereopy".
